# Generated by Django 5.1.2 on 2024-10-29 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_order_customer_email_order_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping',
            name='country',
            field=models.CharField(default='USA', max_length=30),
        ),
    ]
