# Generated by Django 5.1.2 on 2024-10-31 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_order_guest_email_order_guest_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paypal', models.CharField(blank=True, max_length=30, null=True)),
                ('venmo', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
