# Generated by Django 5.1.2 on 2024-11-03 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_paymenttag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentreceipt',
            name='receipt_image',
            field=models.ImageField(upload_to='images/payment_receipts/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
